# Installation von R, RStudio und GIT
Im ersten Tutorium lernt ihr, wie ihr R und RStudio installiert und wie ihr ein Repository auf GitHub erstellt.

## Installation von R
R ist ein Open-Source Programm. Um R zu installieren, wählt man einen nahen Server aus. Wir wählen den Server der Uni Münster: https://cran.uni-muenster.de/.
### Für Windows
Klickt auf „Dowload R for Windows“. Danach geht ihr auf „Install R for the first time“. Wählt „Dowload R 3.4.4 for Windows“, um den Download zu starten. Die .exe Datei landet in eurem Download-Ordner. Anklicken, Installation befolgen, R öffnen.

### Für Mac
Klickt auf „Download R for (Mac) OS X“. Wenn ihr nicht wisst, welches Betriebssystem ihr habt, schaut auf eurem Mac unter „Über diesen Mac“ nach. Wählt dann auf der Web-Seite die richtige .pckg Datei aus, der Klick startet den Download. Im Finder könnt ihr unter „Downloads“ die .pckg Datei auswählen, die Installation befolgen und ebenfalls R öffnen.

## Kleines R Intro
R ist ein Kommandozeilen-Programm. Die Kommandozeile wird durch ein „>“ am Anfang der Zeile angezeigt. Hier schreibt ihr eure Befehle und führt sie mit Enter aus. Mit „#“ könnt ihr Kommentare kennzeichnen. Diese werden nicht ausgeführt, sondern erläutern Befehle und Ausführungen für z.B. eure Gruppenmitglieder.
Ihr könnt euer gesamtes Projekt nur mithilfe von R durchführen. Das ist jedoch vor allem etwas für richtige „Coder“. Es gibt jedoch ein Programm, das uns hilft, mit R leichter und verständlicher umzugehen: RStudio!

## Installation von RStudio
Geht auf https://www.rstudio.com/, wählt Products/RStudio und klickt auf der Seite den Button „Download RStudio Desktop“. In der Tabelle könnt ihr unter „FREE“ auf „Download“ klicken. Die Web-Seite führt euch zu den „Installers for Supported Platforms“. Hier gibt es die Downloads für Windows und Mac OS X.
**R muss vor RStudio installiert sein, da RStudio selbst kein Kommandozeilen-Programm ist, sondern nur eine grafische Oberfläche für R bietet, welche die Benutzung von R erleichtert!**

## Wie erstellt man ein Repository auf GitHub?
GitHub ist eine Art Host, auf dem mehrere Personen gemeinsam an einem Code-Projekt arbeiten können. Mehr dazu im zweiten Tutorium. 

* Zu allererst solltet ihr euch bei GitHub registrieren.
* Oben rechts beim Plus-Zeichen könnt ihr unter „New Repository“ ein solches anlegen. Gebt dem Repository einen Projektnamen.
* Lasst das Repository auf öffentlich, alles andere kostet. Damit kann jede Person eure Dokumente anschauen! Da dies jedoch nur Code-Zeilen sein werden, ist es nicht schlimm. Schreibt aber keine sensiblen Daten in eure Dokumente.
* Drückt „initializie“ und lasst die anderen Einstellungen auf „none“/„none“.
* Erstellt euer Repository!

In die readme Datei könnt ihr eine kurze Erklärung eures späteren Projekts für andere GitHub-User reinschreiben, ihr müsst dies jedoch nicht tun.

## Nice to know

Wenn ihr den Haken bei initialize nicht setzt, zeigt euch GitHub nun im ersten Abschnitt mehrere Code-Zeilen an, die ihr in eurem Terminal (Mac) oder in eurer Eingabeaufforderung (Windows) ausführen könnt. Die Eingabeaufforderung muss als Administrator ausgeführt werden und muss die GIT-Befehle kennen. Da das bei einigen von euch nicht geklappt hat, haltet euch bitte an die obere Erklärung.
An einer Stelle werden euch die Programme darum bitten, euren GitHub Nutzernamen und euer Passwort einzugeben. Beim Passwort bewegt sich der Cursor nicht weiter, lasst euch davon jedoch nicht beirren. Das Programm realisiert trotzdem, dass ihr gerade etwas eingebt, zeigt es aber zu eurem Schutz nicht an. Tippt also einfach euer Passwort ein und bestätigt mit Enter.
Euer Repository sollte auch hier nun angelegt sein.
