# Wochenplan (3. Semester)

## Woche 1: Einführung
* Einführung und Übersicht über die Veranstaltung
* Workload und Prüfungsleistung
* Literatur
* Lernziele und Kompetenzen
* Zeitplan und Gruppeneinteilung

*Aufgaben Woche 1*
* XING-Challenge
* Literatur besorgen: Fuhse, Jan Arendt (2016): [Soziale Netzwerke. Konzepte und Forschungsmethoden.](https://link.springer.com/chapter/10.1007/978-3-531-92575-2_19) Konstanz/München: UVK.
* Installation [SocNetV](http://socnetv.org/downloads/)

*Literatur für Woche 1*
* Krajic, K. (2017): Netzwerke überall? Anmerkungen zum wissenschaftlichen und praktischen Gebrauch von Netzwerk und Netzwerkanalyse. Paediatric Paedology 2017, 52, Suppl. 1: S4–S9; DOI 10.1007/s00608-017-0503-z.
https://link.springer.com/content/pdf/10.1007%2Fs00608-017-0503-z.pdf

## Woche 2: Warum Netzwerke?
* Netzwerke als "the next big thing"
* Soziale Netzwerke vs. Soziale Netzwerkanalyse
* Nutzen von und Kritik an Netzwerken
* Grundbegriffe der sozialen Netzwerkanalyse
* Unterscheidung von Egonetzwerk von Gesamtnetzwerk
* gerichtete und ungerichtete Beziehungen
* two-mode und multiplexe Netzwerke
* Netzwerke im Alltag

*Literatur für Woche 2:* 
* Krüger, U. (2013): [Die Nähe zur Macht](http://www.message-online.com/wp-content/uploads/Artikel_Krueger_Die_Naehe_zur_Macht_Message_1_2013.pdf). In: message, 2013(1), 22-28. 
* Video: [Die Anstalt](https://www.youtube.com/watch?v=y_bmegfMyVI)
* Grimm, R. (2013): [Gespräch mit Mark Granovetter. Die Stärke des Schwachen](https://gdiabo.genios.de/document?id=GDI__D50387D40F7C8AAEC3206E31B8965BDF&src=hitlist&offset=0). In: GDI Impuls 3/2013, 16-21.

*Moodle-Aufgabe:*
* Recherche der Mitgliedschaften eines Journalisten über Wikipedia, Kress, Torial, twitter
* Mini-Test der Kernbegriffe der Netzwerkanalyse

## Woche 3: Klassische Studien und Anwendungen der Netzwerkanalyse
*Klassische Studien*
Jedes Team wählt auf Moodle einen Text aus, bereitet diesen vor und präsentiert die Studie in einer Fishbowl-Diskussion. Dabei nehmen Sie die Rolle des jeweiligen Forschers ein und stellen möglichst überzeugend ihre Ergebnisse vor (5 min pro Team, alle Formen der Präsentation erlaubt, so lange Sie ohne Beamer auskommen).

* Studie 1: Simmel, G. (1908): Die Kreuzung sozialer Kreise. [Text Nollert 2010](https://link.springer.com/chapter/10.1007%2F978-3-531-92575-2_14)
* Studie 2: Rogers, E. M. (1962): Diffusion of Innovations. [Text Karnowski & Kümpel 2016](https://link.springer.com/chapter/10.1007/978-3-658-09923-7_9)
* Studie 3: Milgram, S. (1967): The small world Problem. [Text Stauffer 2010](https://link.springer.com/chapter/10.1007/978-3-531-92575-2_19)
* Studie 4: Granovetter, M. S. (1974): Getting a Job [Text Lutter 2017](https://link.springer.com/chapter/10.1007/978-3-658-08184-3_21)
* Studie 5: Uzzi, B. (1977): Social Structure and Competition in Interfirm Networks [Text Wansleben 2017](https://link.springer.com/chapter/10.1007/978-3-658-08184-3_34)
* Studie 6: Burt, R. S. (1992): Structural Holes [Text Lutter 2017](https://link.springer.com/chapter/10.1007/978-3-658-08184-3_26)
* Studie 7: Krackhardt, D. (1992): The Strength of Strong Ties. [Text Reischauer 2015](https://link.springer.com/chapter/10.1007/978-3-658-09068-5_2)

*Moodle-Aufgaben*
* Zuordnung der Kernaussagen der Ansätze
* Vollerhebung des Datensatzes des Kurses

## Woche 4: Visualisierung: Soziometrie und Graphen
* Moreno's Erbe: Soziometrie
* Aufbau eines Graphs, Konventionen
* Repräsentation eines Graphs: Edgelist, Matrix
* Prämissen guter Visualisierung
* Schnelle Visualisierungstools

*Moodle-Aufgaben*
* Bestandteile einer Edgelist erheben
* Visualisierung Zachary's Karate Club in SocNetV

## Woche 5: Netzwerkmaße und -konfigurationen
* Dyaden, Triaden und Cliquen
* Akteursbezogene Maße: Zentralität, Betweenness
* Netzwerkbezogene Maße: Dichte, Cluster, Pfaddistanz

*Moodle-Aufgaben*
* Bestandteile einer Edgelist erheben
* Analyse & Visualisierung Zachary's Karate Club in SocNetV
* Analyse und Interpretation [Moviegalaxies](http://moviegalaxies.com/)

## Woche 6: Netzwerkmechanismen
* Reziprozität, Homophilie und Transitivität
* Powerlaws: Metcalfe's law

## Woche 7: Sozialkapital und Netzwerke in Organisationen
* Sozialkapital: Grundlagen und Definitionen
* Netzwerke in Organisationen

## Woche 8: Diffusionsforschung
* Diffusion von Innovation
* Meinungsführer in Netzwerken

## Woche 9: Semanatische Netzwerke



## Woche 9: Forschungsdesigns der Netzwerkanalyse

* Installation [R](https://cran.uni-muenster.de/) und [RStudio](https://www.rstudio.com/products/rstudio/download/#download)

## Woche 10/11: Entwicklung eines Forschungsdesigns
* Forschungsfrage und Hypothese
* Datenzugang und Pretest

## Woche 12/13: Präsentation Forschungsdesigns

## Woche 14/15: Wrap-up
* Abgabe überarbeitetes Forschungsdesign





